SiteManagement.Web/Models/ErrorViewModel.cs
using System;

namespace SiteManagement.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SiteManagement.Web/Areas/Admin/Controllers/ApartmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SiteManagament.Core;
using SiteManagament.Core.Entity;
using SiteManagament.Core.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteManagement.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area(nameof(Admin))]
    [Route(nameof(Admin) + "/[controller]")]

    public class ApartmentController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }  
         

        [HttpPost]
        public IActionResult Post([FromBody] Tenant tenant)
        {

            return View();
        }
        //[HttpGet]
        //public IActionResult Get()
        //{
        //    var apartments = _service.GetAllAsync();
        //    return Ok(apartments);

        //}
        //[HttpGet("{id}")]
        //public IActionResult Get(int id)
        //{
        //    var apartments = _service.GetByIdAsync(id);
        //    if (apartments == null)
        //    {
        //        return Ok(apartments);
        //    }
        //    return NotFound();

        //}
        //[HttpPost]
        //public IActionResult Post([FromBody] Apartment apartment)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        var addedApartment = _service.AddAsync(apartment);
        //        return CreatedAtAction("Get", new { id = addedApartment.Id }, addedApartment);
        //    }
        //    else
        //    {
        //        return BadRequest(ModelState); //400+validation errors
        //    }


        //}


        //[HttpPut]
        //public IActionResult Put([FromBody] Apartment aparment)
        //{
        //    if (_service.UpdateAsync(aparment) != null)
        //    {
        //        return Ok(_service.UpdateAsync(aparment)); //200 + data
        //    }

        //    return NotFound();
        //}
        //[HttpDelete]
        //public IActionResult Delete(Apartment aparment)
        //{
        //    if (_service.DeleteAsync(aparment) != null)
        //    {
        //        _service.DeleteAsync(aparment); //200
        //        return Ok();
        //    }

        //    return NotFound(); //404 döndürecek

        //}
    }
    }

SiteManagement.Web/Areas/Admin/Controllers/DuesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SiteManagament.Core.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteManagement.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area(nameof(Admin))]
    [Route(nameof(Admin) + "/[controller]")]
    public class DuesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Post([FromBody] Payment payment)
        {

           
            return View();
        }

    }
}

SiteManagement.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteManagement.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area(nameof(Admin))]
    [Route(nameof(Admin) + "/[controller]")]

    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SiteManagement.Web/Areas/Admin/Controllers/InvoiceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SiteManagament.Core.Entity;
using SiteManagament.Core.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteManagement.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area(nameof(Admin))]
    [Route(nameof(Admin) + "/[controller]")]
    public class InvoiceController : Controller
    {
        public IActionResult Index()
            {
                return View();
            }
      
            [HttpPost]
            public IActionResult Post([FromBody] Payment payment)
            {

            return View();
           
            }


      

    }
}

SiteManagement.Web/Areas/Admin/Controllers/TenantController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SiteManagament.Core;
using SiteManagament.Core.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SiteManagement.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area(nameof(Admin))]
    [Route(nameof(Admin) + "/[controller]")]
    public class TenantController : Controller
    {

            public IActionResult Index()
            {
           
               return View();
             }


        [HttpPost]
        public IActionResult Post([FromBody] Tenant tenant)
        {

            return View();
        }


    }
}

SiteManagement.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SiteManagament.Core;
using SiteManagement.Repository;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SiteManagement.Web.Controllers
{
    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;
        private AppDbContext Db;
        public HomeController(ILogger<HomeController> logger, AppDbContext applicationContext)
        {
            _logger = logger;
            Db = applicationContext;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(string Email,string Password)
        {
            Tenant tenant = Db.Tenants.FirstOrDefault(x => x.Email == Email);
            if (tenant == null)
            {
                return View();
            }
            var result = tenant.Password == Password;
            ClaimsIdentity identity = null;
            bool isAuthenticate = false;
            if (result)
            {
                var tenantRoles = Db.Tenants.Where(ur =>ur.Role.Id == tenant.RoleId);
                var roles = Db.Roles.Where(ro => tenantRoles.Any(ur => ur.Role.Id == ro.Id));
                identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                foreach (var item in roles)
                {
                   identity.AddClaim(new Claim(ClaimTypes.Role, item.RoleName));
                }
                identity.AddClaim(new Claim(ClaimTypes.Email, Email));
                isAuthenticate = true;
            }
            if (isAuthenticate)
            {
                var principal = new ClaimsPrincipal(identity);
                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                return RedirectToAction("Index", "Home", new { Area = "Admin" });
            }
            return View();
        }
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Page()
        {
            return View();
        }

    }
}

SiteManagement.Web/Areas/Admin/Views/Apartment/Index.cshtml
@model SiteManagament.Core.Apartment

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Daire Bilgileri</h1>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="card mb-4">
            <div class="card-body">

                @using (Html.BeginForm("Post", "Apartment", FormMethod.Post, new { }))
                {
                    <table width="100%">
                        <tr>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Daire Bloğu</label>
                                    @Html.TextBoxFor(p => p.ApartmentBlock, new { @class = "form-control", @placeholder = "Dairenin Bloğunu Giriniz" })

                                </div>
                            </td>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Daire Numarası</label>
                                    @Html.TextBoxFor(p => p.ApartmentNumber, new { @class = "form-control", @placeholder = "Daire Numarası Giriniz" })
                                </div>

                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Daire Sahibinin Adı</label>
                                    @Html.TextBoxFor(p => p.ApartmentOwner, new { @class = "form-control", @placeholder = "Daire Sahibini Giriniz" })
                                </div>

                            </td>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Daire Tipi</label>
                                    @Html.TextBoxFor(p => p.ApartmentType, new { @class = "form-control", @placeholder = "Daire Tipini Giriniz" })
                                </div>

                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Daire Durumu</label>
                                    @Html.TextBoxFor(p => p.ApartmentStatus, new { @class = "form-control", @placeholder = "Daire Durumunu Giriniz" })
                                </div>
                            </td>

                        </tr>

                    </table>


                }

                <input type="submit" class="btn btn-primary btn-block style="float:right;" />

            </div>
        </div>

    </div>
</div>

SiteManagement.Web/Areas/Admin/Views/Dues/Index.cshtml
@model SiteManagament.Core.Entity.Payment
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Aidat Ekle</h1>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="card mb-4">
            <div class="card-body">

                @using (Html.BeginForm("Post", "Dues", FormMethod.Post, new { }))
                {
                    <table width="100%">
                        <tr>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Daire Numarası</label>
                                    @Html.TextBoxFor(p => p.aparment.Id, new { @class = "form-control", @placeholder = "Daire Numarası Giriniz" })
                                </div>

                            </td>
                            
                        </tr>
                        <tr>
                            <td>

                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Daire Sahibi</label>
                                    @Html.TextBoxFor(p => p.aparment.ApartmentOwner, new { @class = "form-control", @placeholder = "Daire Sahibini Giriniz" })
                                </div>

                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Aidat Tutarı </label>
                                    @Html.TextBoxFor(p => p.Price, new { @class = "form-control", @placeholder = "Tutar Giriniz" })

                                </div>


                            </td>

                        </tr>
                    </table>


                }

                <input type="submit" class="btn btn-primary btn-block style="float:right;" />

            </div>
        </div>

    </div>
</div>

SiteManagement.Web/Areas/Admin/Views/Invoice/Index.cshtml
@model SiteManagament.Core.Entity.Payment
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Fatura Ekle</h1>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="card mb-4">
            <div class="card-body">

                @using (Html.BeginForm("Post", "Invoice", FormMethod.Post, new { }))
                {
                    <table width="100%">
                        <tr>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Daire Numarası</label>
                                    @Html.TextBoxFor(p => p.aparment.Id, new { @class = "form-control", @placeholder = "Daire Numarası Giriniz" })
                                </div>

                            </td>
                          
                        </tr>
                        <tr>
                            <td>

                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Daire Sahibi</label>
                                    @Html.TextBoxFor(p => p.aparment.ApartmentOwner, new { @class = "form-control", @placeholder = "Daire Sahibini Giriniz" })
                                </div>

                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Fatura Tutarı </label>
                                    @Html.TextBoxFor(p => p.Price, new { @class = "form-control", @placeholder = "Tutar Giriniz" })

                                </div>
                              

                            </td>
                            
                        </tr>
                     </table>


                }

                <input type="submit" class="btn btn-primary btn-block style="float:right;" />

            </div>
        </div>

    </div>
</div>

SiteManagement.Web/Areas/Admin/Views/Tenant/Index.cshtml
@model SiteManagament.Core.Tenant

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Kullanıcı Bilgileri</h1>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="card mb-4">
            <div class="card-body">

                @using (Html.BeginForm("Post", "Tenant", FormMethod.Post, new { }))
                {
                    <table width="100%">
                        <tr>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Adı</label>
                                    @Html.TextBoxFor(p => p.Name, new { @class = "form-control", @placeholder = "Adı Giriniz" })

                                </div>
                            </td>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Soyadı</label>
                                    @Html.TextBoxFor(p => p.Lastname, new { @class = "form-control", @placeholder = "Soyadı Giriniz" })
                                </div>

                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">TC Kimlik No</label>
                                    @Html.TextBoxFor(p => p.IdentificationNumber, new { @class = "form-control", @placeholder = "Tc Kimlik No Giriniz" })
                                </div>

                            </td>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Email</label>
                                    @Html.TextBoxFor(p => p.Email, new { @class = "form-control", @placeholder = "Email Giriniz" })
                                </div>

                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group">
                                    <label for="exampleFormControlInput1">Cep Telefonu</label>
                                    @Html.TextBoxFor(p => p.Phone, new { @class = "form-control", @placeholder = "Cep Telefonu Giriniz" })
                                </div>
                            </td>
                            <td>

                                <div class="form-group">
                                    <label for="exampleFormControlSelect1">Daire Seçiniz</label>
                                   <select class="form-control" id="exampleFormControlSelect1">
                                        <option>A Sitesi 3. kat Daire:5</option>
                                        <option>B Sitesi 3. kat Daire:5</option>
                                        <option>C Sitesi 3. kat Daire:5</option>
                                        <option>D Sitesi 3. kat Daire:5</option>
                                        <option>E Sitesi 3. kat Daire:5</option>
                                    </select>
                                </div>

                            </td>
                        </tr>

                        <tr>
                            <td>
                                <div class="form-group">
                                    <div class="custom-control custom-switch">
                                        @Html.RadioButtonFor(m => m.IsHaveCar, "Araba mevcut mu ?")<label>Araba Mevcut Mu?</label>
                                    
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="form-group">
                                    @Html.TextBoxFor(p => p.CarPlateNumber, new { @class = "form-control", @placeholder = "Plakasını Giriniz" })
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="form-group">
                                    <div class="custom-control custom-radio">
                                        @Html.RadioButtonFor(m => m.Role, "Admin")<label>Admin</label>
                                    </div>
                                    <div class="custom-control custom-radio">
                                        @Html.RadioButtonFor(m => m.Role, "Kullanıcı")<label>Kullanıcı</label>
                                    </div>

                                </div>
                            </td>
                            <td>
                                <input type="submit" class="btn btn-primary btn-block style="float:right;" />
                            </td>
                        </tr>
                    </table>
                }



            </div>
        </div>

    </div>
</div>

SiteManagement.Web/Views/Home/Index.cshtml
@model SiteManagament.Core.Tenant
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="img/logo/logo.png" rel="icon">
    <title>RuangAdmin - Login</title>
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="css/ruang-admin.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-login">
    <!-- Login Content -->
    <div class="container-login">
        <div class="row justify-content-center">
            <div class="col-xl-6 col-lg-12 col-md-9">
                <div class="card shadow-sm my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="login-form">
                                   
                                        @using (Html.BeginForm("Index", "Home", FormMethod.Post))
                                        {

                                        <div class="form-group">
                                            @Html.TextBoxFor(p => p.Email, new { @class = "form-control", @aria_describedby = "emailHelp", @placeholder = "Email Adresi Giriniz" })
                                            
                                        </div>

                                        <div class="form-group">
                                            @Html.PasswordFor(p => p.Password, new { @class = "form-control", @placeholder = "Şifreyi Giriniz" })
                
                                        </div>

                                        <div class="form-group">
                                            <input type="submit" class="btn btn-primary btn-block" />
                                            
                                        </div>
                                        
                                        }
                                    
                                    <hr>   
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Login Content -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="js/ruang-admin.min.js"></script>
</body>

</html>

SiteManagement.Web/Views/Home/Page.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
ön yüz